name: Build Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos & SDK
        run: |
          sudo apt-get update
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          git clone https://github.com/theos/sdks.git $HOME/theos/sdks/
        
      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          make package
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameKeyProtector-Package
          path: packages/*.deb
